### ISSUE TITLE
Title is overwritten by "userstatus wwu" when in admin-settings

### ISSUE THREAD

**Issue by Nullmann** [learnweb/moodle-tool_cleanupusers#1]
When on the normal admin settings page (/admin/search.php), the title is replaced, see:

![screenshot](https://user-images.githubusercontent.com/15816473/35232945-14513fca-ff9d-11e7-97a7-1bd28ef6217a.jpg)

System: Linux, Moodle-Version 3.4 with boost theme (and boost_campus).

**Comment by Dagefoerde** [comment]
Hi @Nullmann, thanks for noticing this and the other thing (#2). Both should be fixed in the version that is now on master (still WIP, though).
