### ISSUE TITLE
renderer.php 

### ISSUE THREAD

**Issue by Dmfama20** [learnweb/moodle-tool_cleanupusers#24]
Hi,
I've noticed an issue concerning Moodle 3.11.3+ (Build: 20211019).  In the "general settings" menu there are the following debugging messages:
-Notice: Undefined variable: cleanupusers in /var/www/html/admin/tool/cleanupusers/renderer.php on line 62

-Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/admin/tool/cleanupusers/renderer.php on line 276

Thank you!

Alex

**Comment by NinaHerrmann** [comment]
Hey Alex, 
thanks for reporting, feel free to submit a pull request fixing the issues!
Best, 
Nina
