### ISSUE TITLE
The function for deleting users exceeds 100 characters

### ISSUE THREAD

**Issue by Nullmann** [learnweb/moodle-tool_cleanupusers#5]
Hello @Dagefoerde ,

we at the TUDarmstadt wrote a subplugin for using your plugin together with our LDAP-Server. While testing, we found out that the delete_me-function does not work as intended:
https://github.com/learnweb/moodle-tool_cleanupusers/blob/master/classes/archiveduser.php#L230-L235

In the selected comments, you wrote that the characters cannot exceed 100 characters, but this is not true (for us, it is 103 characters), as the core code for deleting a user has an additonal user-id beforehand, see: https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L4148

Doing a git-log for this specific line it seems like this was the case the whole time, as it was created this way and not changed since:
git log --pretty=short -u -L 4155,4155:lib/moodlelib.php

A quick fix for this would be to truncate the sha256-hash (is it used afterwards anywhere?) or to use an md5-hash which results in 32 characters instead of 64.

Best regards,
Benedikt

**Comment by Dagefoerde** [comment]
@NinaHerrmann could you please have a look?

**Comment by NinaHerrmann** [comment]
Hello @Nullmann,
Thanks for testing the plugin! 
Just to make sure I understood your problem correctly: 
When trying to use the plugin you have some user with no e-mail address.  In this case, the core function tries to set the username to :
``` $user->email : $user->username . '.' . $user->id . '@unknownemail.invalid'```
and you get an error that the name is too long for the database right?

In this case, using the md5-hash would also be my first choice to fix the error in the plugin. However, the moodle code only makes partial sense to me. As far as I can see the e-mail column is notnull, so why do you have users without an e-mail?

**Comment by Nullmann** [comment]
Hello @NinaHerrmann,
yes you understood the problem correctly. We actually don't have users which don't have a mail adress, but when a user gets suspended, the mdl_user-table gets anonymised. This includes deleting the mail for the user (and backing it up in your table), thus resulting in the moodle code's branch for having a null-mail.

Best regards.

**Comment by NinaHerrmann** [comment]
Hey again, 
in this case, I think I"ll rather prefer to set a pseudo e-mail, instead of leaving the field empty and changing the hash function.
This should solve the problem as well but I will need to test that.
I would be happy to receive further feedback from you about the plugin. :+1:  
Best Regards, 
Nina

**Comment by Nullmann** [comment]
Hello @NinaHerrmann,

what's the status for this issue? We would like to use your plugin as soon as possible. Otherwise we would likely fix this ourselves by using the md5-hash.

With best regards,
Benedikt

**Comment by NinaHerrmann** [comment]
Hey :) 
We are still in the testing phase, so if you don't mind just clone the repository and change the line. 
If my proposed solution works out, you can still adopt it, when I am implementing it.
Best Regards, 
Nina

**Comment by Nullmann** [comment]
@NinaHerrmann I finally managed to (re)do the changes and requestes a pull request here: https://github.com/learnweb/moodle-tool_cleanupusers/pull/8

Sadly, the Travis CI failed due to too old configuration.

**Comment by NinaHerrmann** [comment]
I am closing this since the pull request is merged (a571aa8d24c92c91ce985ad562c87c8a676db8bd).
