### ISSUE TITLE
Count() of array

### ISSUE THREAD

**Issue by NinaHerrmann** [learnweb/moodle-tool_cleanupusers#7]
In userstatus/userstatuswwu/classes/userstatuswwu.php l. 168  count(groups) is throwing a warning.

**Comment by Dagefoerde** [comment]
Which one?

**Comment by NinaHerrmann** [comment]
L 168

**Comment by tobiasreischmann** [comment]
For future reference: https://github.com/learnweb/moodle-tool_cleanupusers/blob/e614569f7966de9bac55d227da65fa168bcfe678/userstatus/userstatuswwu/classes/userstatuswwu.php#L168
;)

**Comment by Dagefoerde** [comment]
Fair enough, but which warning is thrown? @ninaherrmann

**Comment by NinaHerrmann** [comment]
Funny story. Actually, my phpunit test would have covered that case. However, they did not fail since they run on php 7.1. Locally I have php 7.2 installed and saw the warning in my local instance (It would not have been visible without debugging mode on so for production it was not an issue). 
Since 7.2 `count(null)` throws a warning. 

```count(): Parameter must be an array or an object that implements Countable``` 

The commit adjustment fixes it by first checking equality with `null`. 

I will close the issue when the branch is merged.
